//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

class ___FILEBASENAMEASIDENTIFIER___ {
    // MARK: Business Logic
    
    func doSomeWork() {
        // NOTE: Do the work
    }
}
