//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

import Swinject


class ___FILEBASENAMEASIDENTIFIER___: Assembly {
    
    func assemble(container: Container) {
        
//        container.register(ExampleService.self) { _ in
//            ExampleServiceImpl()
//        }.inObjectScope(.container)
        
    }
}
