//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml


import SwiftRouting
import UIKit


class ___VARIABLE_navigatorName___Navigator: IAppNavigator{
    
    static var _navigator: AppNavigator?
    
    static var shared: AppNavigator{
        _navigator!
    }
    
    // Call this method before use the shared instance
    static func initialize(window: UIWindow){
        _navigator = AppNavigator(window: window)
    }
    
    weak var window: UIWindow!
    
    private init(window: UIWindow){
        self.window = window
    }
    
}
