//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

import Foundation

// MARK: Interactor Requests interface
protocol I___VARIABLE_sceneName___SceneInteractor: AnyObject{
    
}

class ___VARIABLE_sceneName___SceneInteractor {
    
    var presenter: I___VARIABLE_sceneName___ScenePresenter
    
    /*
     var worker1: Worker1
     var worker2: Worker2
     */
    
    init(presenter: I___VARIABLE_sceneName___ScenePresenter /*, dependency1: Dependency1, dependency2: Dependency2 */){
        self.presenter = presenter
        /*
         self.worker1 = Worker1(dependency1)
         self.worker2 = Worker2(dependency2)
         */
    }

}

extension ___VARIABLE_sceneName___SceneInteractor: I___VARIABLE_sceneName___SceneInteractor{
    // MARK: BUSINESS LOGIC INTERFACE IMPLEMENTATIONS
}
