//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

protocol I___VARIABLE_sceneName___ScenePresenter: AnyObject {
    
}

class ___VARIABLE_sceneName___ScenePresenter{
    
    weak var vc: I___VARIABLE_sceneName___SceneDelegate?
    
    init(vc: I___VARIABLE_sceneName___SceneDelegate){
        self.vc = vc
    }
}

extension ___VARIABLE_sceneName___ScenePresenter: I___VARIABLE_sceneName___ScenePresenter{
    // MARK: PRESENTATION LOGIC INTERFACE IMPLEMENTATIONS
}
