//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

import Swinject
import SwiftRouting

extension ___VARIABLE_sceneName___SceneViewController: XibImportable{}

class ___VARIABLE_sceneName___SceneAdapter {
    
    private init() {}
    
    // MARK: Dependency Injection
    static func setup(input: ___VARIABLE_sceneName___.Input? = nil, assembler: Assembler? = nil) -> UIViewController{
        
        guard let assembler = assembler,
              let navigator = assembler.resolver.resolve(IAppNavigator.self)
            // Add more dependency here
        else {
            fatalError("Dependencies not found")
        }
        
        let newAssembler = Assembler(parentAssembler: assembler)
        
        let controller = ___VARIABLE_sceneName___SceneViewController.fromXib()
        let router = ___VARIABLE_sceneName___SceneRouter(vc: controller)
        let presenter = ___VARIABLE_sceneName___ScenePresenter(vc: controller)
        let interactor = ___VARIABLE_sceneName___SceneInteractor(presenter: presenter)
        
        controller.router = router
        controller.interactor = interactor
        controller.input = input
        
        router.assembler = newAssembler
        router.navigator = navigator
        
        return controller
    }
}
