//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml


struct ___VARIABLE_sceneName___SceneModels {
    struct Input{
        
    }
}

// MARK: Models for passing data to other routes
extension ___VARIABLE_sceneName___SceneModels{
    
}


// MARK: VIP - USE CASES
extension ___VARIABLE_sceneName___SceneModels{
    // type `usecases` for magic
}
