//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

import UIKit

// MARK: Controller Delegate
protocol I___VARIABLE_sceneName___SceneDelegate: AnyObject{
    
}

class ___VARIABLE_sceneName___SceneViewController: UIViewController {
    
    var router: I___VARIABLE_sceneName___SceneRouter!
    var interactor: I___VARIABLE_sceneName___SceneInteractor!
    var input: ___VARIABLE_sceneName___.Input?
    
    // MARK: OUTLETS
    
    
    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    
}

extension ___VARIABLE_sceneName___SceneViewController: I___VARIABLE_sceneName___SceneDelegate{
    // MARK: DISPLAY LOGIC IMPLEMENTATION INTERFACE
}
