//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

import UIKit
import SwiftRouting
import Swinject


// MARK: Navigation Methods
protocol I___VARIABLE_sceneName___SceneRouter: AnyObject{

}

class ___VARIABLE_sceneName___SceneRouter: IRouter {
    
    enum AvailableRoutes {
        case example(input: ___VARIABLE_sceneName___SceneAdapter? = nil)
    }
    
    typealias Routes = AvailableRoutes
    
    weak var vc: UIViewController!
    var navigator: IAppNavigator?
    var assembler: Assembler?
    
    init(vc: UIViewController) {
        self.vc = vc
    }
    
    func showRoute(route: AvailableRoutes) {
        
        switch route{
        case .example(let input): break
//            let controller = ExampleSceneAdapter.setup(input: input, assembler: assembler)
//            navigator?.go(from: vc, to: controller)
        }
    }

}


extension ___VARIABLE_sceneName___SceneRouter: I___VARIABLE_sceneName___SceneRouter{
    // MARK: NAVIGATION METHODS LOGIC INTERFACE IMPLEMENTATION
    
}
