//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

import UIKit
import Swinject
import SwiftRouting

enum BaseRoutes{
    
    case home(input: String)

}

class BaseRouter: IRouter{
    
    typealias Routes = BaseRoutes
    
    private(set) var navigator: IAppNavigator?
    private(set) var assembler: Assembler?
    
    
    init(_ router: IAppNavigator, assembler: Assembler?){
        self.navigator = router
        self.assembler = assembler
    }
    
    func showRoute(route: BaseRoutes){
        switch route {
        case .home(let input):
//            let controller = HomeSceneAdapter.setup(input: input, assembler: assembler)
//            navigator!.setRootController(rootType: .singleStack(controller: controller)
            break
        }
    }
    
}
